Preparing the PAAL ADL dataset (Climent-Perez_Munoz-Anton_Poli, 2022) for the analysis. Dataset downloaded from: https://zenodo.org/records/5785955

In [ ]:
import os
import warnings
from pathlib import Path
import pandas as pd

# Suppress warnings from Python and external libraries
os.environ["PYTHONWARNINGS"] = "ignore"  # Suppress Python warnings
warnings.filterwarnings("ignore")

In [ ]:
fs = 32  # Hz, from PAAL ADL dataset description (Climent-Perez_Munoz-Anton_Poli, 2022)
time_per_sample = 1000 / fs  # milliseconds per sample

In [ ]:
metadata_df = pd.read_csv('../Data/PAAL_ADL/Raw/ADLs.csv', header=None)
metadata_df

     0                   1
0    1         drink water
1    2            eat meal
2    3         open bottle
3    4          open a box
4    5         brush teeth
5    6          brush hair
6    7     take off jacket
7    8       put on jacket
8    9       put on a shoe
9   10     take off a shoe
10  11      put on glasses
11  12    take off glasses
12  13            sit down
13  14            stand up
14  15             writing
15  16          phone call
16  17  type on a keyboard
17  18              salute
18  19        sneeze/cough
19  20           blow nose
20  21       washing hands
21  22             dusting
22  23             ironing
23  24      washing dishes

In [ ]:
activity_dict = dict(zip(metadata_df[0], metadata_df[1]))
activity_dict

{1: 'drink water',
 2: 'eat meal',
 3: 'open bottle',
 4: 'open a box',
 5: 'brush teeth',
 6: 'brush hair',
 7: 'take off jacket',
 8: 'put on jacket',
 9: 'put on a shoe',
 10: 'take off a shoe',
 11: 'put on glasses',
 12: 'take off glasses',
 13: 'sit down',
 14: 'stand up',
 15: 'writing',
 16: 'phone call',
 17: 'type on a keyboard',
 18: 'salute',
 19: 'sneeze/cough',
 20: 'blow nose',
 21: 'washing hands',
 22: 'dusting',
 23: 'ironing',
 24: 'washing dishes'}

In [ ]:
# Correcting the activity_dict to match the data names in the UiS4ADL dataset
activity_dict[3] = 'open a bottle'
activity_dict[7] = 'take off a jacket'
activity_dict[8] = 'put on a jacket'

In [ ]:
data_dir_path = Path('../Data/PAAL_ADL/Raw/dataset')

# Iterate through all files in the directory
for file_path in data_dir_path.rglob("*.csv"):
    if file_path.is_file():
        print(f"File: {file_path}")
    elif file_path.is_dir():
        print(f"Directory: {file_path}")

File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_45_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_37_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_30_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_5_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_shoe_10_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_25_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_43_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_26_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_38_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_49_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_shoe_36_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/blow_nose_32_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_11_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_16_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_6_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_46_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_5_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_9_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_25_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_36_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_48_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_6_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_7_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_3_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_42_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_45_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_46_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_3_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_48_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_21_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_8_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_6_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_27_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_38_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_dishes_20_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_44_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_44_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_29_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_27_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_dishes_43_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_bottle_12_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_47_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_36_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_33_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_bottle_34_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_48_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_24_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_31_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_27_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_1_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_shoe_12_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_32_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_35_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_47_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_28_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_44_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_4_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_14_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_38_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_36_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_13_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_2_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_9_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_51_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_shoe_34_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_24_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_40_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_5_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_29_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_5_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_27_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_24_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_7_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_23_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_29_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_44_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_47_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_52_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_48_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_46_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_dishes_22_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_9_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_25_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_28_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_19_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_dishes_41_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_25_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_46_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_27_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_45_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_bottle_10_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_39_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_29_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_18_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_26_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_bottle_36_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_24_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_30_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_15_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/blow_nose_36_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_18_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_50_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_47_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_7_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_dishes_39_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_shoe_14_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_shoe_51_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_16_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_18_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/blow_nose_10_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_25_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_14_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_7_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_51_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_41_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_3_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_3_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_2_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_32_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_21_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_37_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_15_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_dishes_47_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_50_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_21_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_4_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_19_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_40_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_23_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_2_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_42_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_33_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_11_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_29_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_19_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_51_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_35_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_38_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_11_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_14_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_32_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_37_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_32_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_43_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_14_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_13_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_51_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_20_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/blow_nose_34_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_32_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_10_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_26_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_40_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/blow_nose_12_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_14_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_51_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_5_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_45_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_bottle_9_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_5_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_16_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_3_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_30_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_19_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_1_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_49_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_6_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_48_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_18_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_23_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_52_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_9_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_35_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_31_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_13_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_40_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_bottle_32_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_30_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_16_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_13_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_18_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_37_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_11_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_16_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_2_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_30_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_35_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_11_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_35_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_30_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_2_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_16_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_13_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_16_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_30_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_37_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_18_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_22_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_40_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_13_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_31_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_dishes_26_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_52_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_23_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_18_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_48_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_6_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_35_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_21_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_42_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_9_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_30_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_19_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_20_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_44_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_1_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_5_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_40_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_16_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_31_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_14_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/blow_nose_12_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_bottle_9_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_45_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_5_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_51_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_shoe_30_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_26_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_32_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/blow_nose_34_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_14_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_bottle_16_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_32_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_37_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_51_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_13_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_38_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_35_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_51_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_19_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_32_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_14_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_11_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_2_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_19_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_29_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_11_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_33_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_42_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_15_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_37_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_4_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_21_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_50_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_3_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_7_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_32_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_2_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_28_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_14_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_51_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_teeth_7_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_1_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_dishes_39_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_7_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_47_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_21_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_41_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/blow_nose_10_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_16_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_18_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_34_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/blow_nose_36_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_30_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_24_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_18_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_26_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_52_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_34_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_bottle_36_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_12_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_17_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_bottle_10_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_45_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_50_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_29_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_15_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_46_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_25_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_dishes_41_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_39_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_25_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_9_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_dishes_22_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_48_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_46_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/type_on_a_keyboard_19_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_12_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_23_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_47_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_44_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_29_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_29_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_1_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_5_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_40_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_7_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_24_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_27_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_2_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_13_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_14_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_44_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_4_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_24_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_shoe_34_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_51_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_7_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_shoe_12_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_27_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_28_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_47_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/blow_nose_16_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_35_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/brush_hair_32_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/phone_call_48_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_bottle_34_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_24_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_38_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_4_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/stand_up_47_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_bottle_12_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/salute_49_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_dishes_43_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_29_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_27_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_44_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/eat_meal_46_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/dusting_37_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_shoe_48_4.csv
File: ../Data/PAAL_ADL/Raw/dataset/drink_water_44_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_dishes_20_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_glasses_27_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_46_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_45_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_21_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/open_a_box_48_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_jacket_48_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/ironing_25_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/sneeze_cough_26_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/washing_hands_9_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/sit_down_5_3.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_glasses_42_2.csv
File: ../Data/PAAL_ADL/Raw/dataset/writing_3_0.csv
File: ../Data/PAAL_ADL/Raw/dataset/put_on_a_shoe_7_1.csv
File: ../Data/PAAL_ADL/Raw/dataset/take_off_a_shoe_36_2.csv

## Combine all files into one PAAL_ADL dataset

In [ ]:
# Reverse activity_dict for quick name lookup
activity_name_to_id = {v.replace("/", " "): k for k, v in activity_dict.items()}

all_data = []
file_id = 1

In [ ]:
activity_name_to_id

{'drink water': 1,
 'eat meal': 2,
 'open a bottle': 3,
 'open a box': 4,
 'brush teeth': 5,
 'brush hair': 6,
 'take off a jacket': 7,
 'put on a jacket': 8,
 'put on a shoe': 9,
 'take off a shoe': 10,
 'put on glasses': 11,
 'take off glasses': 12,
 'sit down': 13,
 'stand up': 14,
 'writing': 15,
 'phone call': 16,
 'type on a keyboard': 17,
 'salute': 18,
 'sneeze cough': 19,
 'blow nose': 20,
 'washing hands': 21,
 'dusting': 22,
 'ironing': 23,
 'washing dishes': 24}

In [ ]:
# Read an example file to analyse its structure
example_file_path = "../Data/PAAL_ADL/Raw/dataset/take_off_a_jacket_45_1.csv"
example_file = pd.read_csv(example_file_path, header=None) # PAAL ADL contains only accelometer data, given in raw counts
example_file

        0     1     2
0   -76.0   8.0 -40.0
1   -55.0   7.0 -34.0
2   -53.0   4.0 -32.0
3   -54.0   5.0 -27.0
4   -64.0   8.0 -29.0
..    ...   ...   ...
194 -74.0 -16.0   5.0
195 -58.0 -20.0  -5.0
196 -64.0 -16.0 -12.0
197 -71.0  -9.0 -27.0
198 -55.0  -9.0 -27.0

[199 rows x 3 columns]

In [ ]:
# Read all the CSV files and collect accelerometer data into one dataframe
# Create a timestamp column and add metadata (adl, session, subject) from the filename. 
# Also create file_id column which is incremented for each file.
for file_path in data_dir_path.rglob("*.csv"):
    if file_path.is_file():
        filename = file_path.stem  # without .csv
        parts = filename.split('_')
        
        # Extract metadata
        subject = int(parts[-2])
        session = int(parts[-1])
        adl_name = " ".join(parts[:-2])
        adl_id = activity_name_to_id[adl_name]
        print(f"ADL: '{adl_name}' ({adl_id}), Subject: {subject}, Session: {session}", end="\n\n")
        
        # Read CSV files containing raw accelerometer data in counts
        # Empatica E4 uses ±2g range with 64 counts = 1g conversion factor 
        # (from: https://www.sciencedirect.com/science/article/pii/S2352340922001081)
        data_df = pd.read_csv(file_path, header=None, names=['accX[counts]', 'accY[counts]', 'accZ[counts]'])
        
        # Convert counts to milligravity (mg)
        # 1 count = 1g / 64 = 1000mg / 64 = 15.625 mg/count
        COUNTS_TO_MG = 1000 / 64  # = 15.625 mg/count
        
        data_df['accX[mg]'] = data_df['accX[counts]'] * COUNTS_TO_MG
        data_df['accY[mg]'] = data_df['accY[counts]'] * COUNTS_TO_MG
        data_df['accZ[mg]'] = data_df['accZ[counts]'] * COUNTS_TO_MG
        
        # Drop the count columns
        data_df = data_df.drop(columns=['accX[counts]', 'accY[counts]', 'accZ[counts]'])
        
        # Add derived columns
        data_df['timestamp'] = (data_df.index * time_per_sample).astype(float)
        data_df['adl'] = adl_id
        data_df['session'] = session
        data_df['subject'] = subject
        data_df['fileID'] = file_id
        
        all_data.append(data_df)
        file_id += 1

ADL: 'take off a jacket' (7), Subject: 45, Session: 1

ADL: 'salute' (18), Subject: 37, Session: 3

ADL: 'brush hair' (6), Subject: 30, Session: 1

ADL: 'brush hair' (6), Subject: 5, Session: 1

ADL: 'take off a shoe' (10), Subject: 10, Session: 0

ADL: 'put on a shoe' (9), Subject: 25, Session: 1

ADL: 'type on a keyboard' (17), Subject: 43, Session: 4

ADL: 'take off a jacket' (7), Subject: 26, Session: 2

ADL: 'eat meal' (2), Subject: 38, Session: 3

ADL: 'dusting' (22), Subject: 49, Session: 3

ADL: 'take off a shoe' (10), Subject: 36, Session: 3

ADL: 'blow nose' (20), Subject: 32, Session: 4

ADL: 'salute' (18), Subject: 11, Session: 0

ADL: 'brush hair' (6), Subject: 16, Session: 2

ADL: 'take off glasses' (12), Subject: 6, Session: 3

ADL: 'put on a shoe' (9), Subject: 46, Session: 2

ADL: 'sit down' (13), Subject: 5, Session: 2

ADL: 'washing hands' (21), Subject: 9, Session: 3

ADL: 'ironing' (23), Subject: 25, Session: 0

ADL: 'phone call' (16), Subject: 36, Session: 4

ADL: 'put on a jacket' (8), Subject: 48, Session: 1

ADL: 'take off a jacket' (7), Subject: 6, Session: 4

ADL: 'put on a shoe' (9), Subject: 7, Session: 0

ADL: 'writing' (15), Subject: 3, Session: 1

ADL: 'take off glasses' (12), Subject: 42, Session: 3

ADL: 'sneeze cough' (19), Subject: 45, Session: 0

ADL: 'ironing' (23), Subject: 46, Session: 3

ADL: 'brush teeth' (5), Subject: 3, Session: 4

ADL: 'open a box' (4), Subject: 48, Session: 2

ADL: 'take off glasses' (12), Subject: 21, Session: 0

ADL: 'put on glasses' (11), Subject: 8, Session: 4

ADL: 'stand up' (14), Subject: 6, Session: 4

ADL: 'put on glasses' (11), Subject: 27, Session: 0

ADL: 'put on a shoe' (9), Subject: 38, Session: 4

ADL: 'washing dishes' (24), Subject: 20, Session: 3

ADL: 'drink water' (1), Subject: 44, Session: 0

ADL: 'put on glasses' (11), Subject: 44, Session: 3

ADL: 'washing hands' (21), Subject: 29, Session: 3

ADL: 'drink water' (1), Subject: 27, Session: 3

ADL: 'washing dishes' (24), Subject: 43, Session: 0

ADL: 'open a bottle' (3), Subject: 12, Session: 1

ADL: 'stand up' (14), Subject: 47, Session: 0

ADL: 'open a box' (4), Subject: 36, Session: 4

ADL: 'sit down' (13), Subject: 33, Session: 4

ADL: 'open a bottle' (3), Subject: 34, Session: 2

ADL: 'phone call' (16), Subject: 48, Session: 2

ADL: 'stand up' (14), Subject: 24, Session: 3

ADL: 'writing' (15), Subject: 31, Session: 4

ADL: 'put on a shoe' (9), Subject: 27, Session: 3

ADL: 'salute' (18), Subject: 1, Session: 4

ADL: 'take off a shoe' (10), Subject: 12, Session: 2

ADL: 'brush hair' (6), Subject: 32, Session: 3

ADL: 'salute' (18), Subject: 35, Session: 1

ADL: 'take off a jacket' (7), Subject: 47, Session: 3

ADL: 'dusting' (22), Subject: 28, Session: 2

ADL: 'put on a shoe' (9), Subject: 44, Session: 0

ADL: 'take off glasses' (12), Subject: 4, Session: 1

ADL: 'brush hair' (6), Subject: 14, Session: 0

ADL: 'drink water' (1), Subject: 38, Session: 4

ADL: 'washing hands' (21), Subject: 36, Session: 4

ADL: 'salute' (18), Subject: 13, Session: 2

ADL: 'ironing' (23), Subject: 2, Session: 0

ADL: 'phone call' (16), Subject: 9, Session: 4

ADL: 'brush hair' (6), Subject: 51, Session: 0

ADL: 'take off a shoe' (10), Subject: 34, Session: 1

ADL: 'take off a jacket' (7), Subject: 24, Session: 0

ADL: 'take off glasses' (12), Subject: 40, Session: 1

ADL: 'put on a shoe' (9), Subject: 5, Session: 2

ADL: 'open a box' (4), Subject: 29, Session: 3

ADL: 'eat meal' (2), Subject: 5, Session: 4

ADL: 'ironing' (23), Subject: 27, Session: 2

ADL: 'sneeze cough' (19), Subject: 24, Session: 1

ADL: 'sit down' (13), Subject: 7, Session: 0

ADL: 'take off glasses' (12), Subject: 23, Session: 2

ADL: 'put on a jacket' (8), Subject: 29, Session: 0

ADL: 'ironing' (23), Subject: 44, Session: 1

ADL: 'sneeze cough' (19), Subject: 47, Session: 2

ADL: 'brush teeth' (5), Subject: 52, Session: 4

ADL: 'washing hands' (21), Subject: 48, Session: 2

ADL: 'drink water' (1), Subject: 46, Session: 2

ADL: 'washing dishes' (24), Subject: 22, Session: 1

ADL: 'type on a keyboard' (17), Subject: 9, Session: 0

ADL: 'put on glasses' (11), Subject: 25, Session: 2

ADL: 'salute' (18), Subject: 28, Session: 4

ADL: 'type on a keyboard' (17), Subject: 19, Session: 3

ADL: 'washing dishes' (24), Subject: 41, Session: 2

ADL: 'drink water' (1), Subject: 25, Session: 1

ADL: 'put on glasses' (11), Subject: 46, Session: 1

ADL: 'eat meal' (2), Subject: 27, Session: 4

ADL: 'stand up' (14), Subject: 45, Session: 2

ADL: 'open a bottle' (3), Subject: 10, Session: 3

ADL: 'sneeze cough' (19), Subject: 39, Session: 4

ADL: 'phone call' (16), Subject: 29, Session: 3

ADL: 'take off glasses' (12), Subject: 18, Session: 4

ADL: 'stand up' (14), Subject: 26, Session: 1

ADL: 'open a bottle' (3), Subject: 36, Session: 0

ADL: 'type on a keyboard' (17), Subject: 24, Session: 3

ADL: 'washing hands' (21), Subject: 30, Session: 2

ADL: 'salute' (18), Subject: 15, Session: 4

ADL: 'blow nose' (20), Subject: 36, Session: 0

ADL: 'put on glasses' (11), Subject: 18, Session: 2

ADL: 'salute' (18), Subject: 50, Session: 4

ADL: 'type on a keyboard' (17), Subject: 47, Session: 0

ADL: 'salute' (18), Subject: 7, Session: 2

ADL: 'washing dishes' (24), Subject: 39, Session: 2

ADL: 'take off a shoe' (10), Subject: 14, Session: 4

ADL: 'take off a shoe' (10), Subject: 51, Session: 4

ADL: 'washing hands' (21), Subject: 16, Session: 1

ADL: 'drink water' (1), Subject: 18, Session: 1

ADL: 'blow nose' (20), Subject: 10, Session: 3

ADL: 'take off glasses' (12), Subject: 25, Session: 4

ADL: 'phone call' (16), Subject: 14, Session: 3

ADL: 'brush teeth' (5), Subject: 7, Session: 0

ADL: 'phone call' (16), Subject: 51, Session: 3

ADL: 'sneeze cough' (19), Subject: 41, Session: 4

ADL: 'put on a shoe' (9), Subject: 3, Session: 4

ADL: 'eat meal' (2), Subject: 3, Session: 2

ADL: 'take off a jacket' (7), Subject: 2, Session: 0

ADL: 'phone call' (16), Subject: 32, Session: 0

ADL: 'ironing' (23), Subject: 21, Session: 4

ADL: 'brush teeth' (5), Subject: 37, Session: 1

ADL: 'dusting' (22), Subject: 15, Session: 2

ADL: 'washing dishes' (24), Subject: 47, Session: 4

ADL: 'dusting' (22), Subject: 50, Session: 2

ADL: 'eat meal' (2), Subject: 21, Session: 2

ADL: 'put on a jacket' (8), Subject: 4, Session: 0

ADL: 'take off a jacket' (7), Subject: 19, Session: 0

ADL: 'drink water' (1), Subject: 40, Session: 4

ADL: 'put on glasses' (11), Subject: 23, Session: 4

ADL: 'stand up' (14), Subject: 2, Session: 0

ADL: 'eat meal' (2), Subject: 42, Session: 1

ADL: 'dusting' (22), Subject: 33, Session: 1

ADL: 'brush teeth' (5), Subject: 11, Session: 2

ADL: 'brush hair' (6), Subject: 29, Session: 0

ADL: 'sneeze cough' (19), Subject: 19, Session: 1

ADL: 'open a box' (4), Subject: 51, Session: 3

ADL: 'writing' (15), Subject: 35, Session: 0

ADL: 'take off glasses' (12), Subject: 38, Session: 1

ADL: 'sit down' (13), Subject: 11, Session: 3

ADL: 'open a box' (4), Subject: 14, Session: 3

ADL: 'put on a jacket' (8), Subject: 32, Session: 3

ADL: 'sit down' (13), Subject: 37, Session: 0

ADL: 'open a box' (4), Subject: 32, Session: 0

ADL: 'stand up' (14), Subject: 43, Session: 4

ADL: 'put on a jacket' (8), Subject: 14, Session: 0

ADL: 'writing' (15), Subject: 13, Session: 3

ADL: 'put on a jacket' (8), Subject: 51, Session: 0

ADL: 'take off a jacket' (7), Subject: 20, Session: 4

ADL: 'blow nose' (20), Subject: 34, Session: 2

ADL: 'washing hands' (21), Subject: 32, Session: 0

ADL: 'brush hair' (6), Subject: 10, Session: 4

ADL: 'type on a keyboard' (17), Subject: 26, Session: 1

ADL: 'put on a shoe' (9), Subject: 40, Session: 4

ADL: 'blow nose' (20), Subject: 12, Session: 1

ADL: 'washing hands' (21), Subject: 14, Session: 3

ADL: 'washing hands' (21), Subject: 51, Session: 3

ADL: 'salute' (18), Subject: 5, Session: 0

ADL: 'type on a keyboard' (17), Subject: 45, Session: 2

ADL: 'open a bottle' (3), Subject: 9, Session: 2

ADL: 'brush teeth' (5), Subject: 5, Session: 2

ADL: 'phone call' (16), Subject: 16, Session: 1

ADL: 'sit down' (13), Subject: 3, Session: 4

ADL: 'phone call' (16), Subject: 30, Session: 2

ADL: 'stand up' (14), Subject: 19, Session: 3

ADL: 'eat meal' (2), Subject: 1, Session: 0

ADL: 'writing' (15), Subject: 49, Session: 4

ADL: 'put on a jacket' (8), Subject: 6, Session: 2

ADL: 'brush hair' (6), Subject: 48, Session: 1

ADL: 'put on a shoe' (9), Subject: 18, Session: 1

ADL: 'eat meal' (2), Subject: 23, Session: 0

ADL: 'dusting' (22), Subject: 52, Session: 0

ADL: 'sneeze cough' (19), Subject: 9, Session: 3

ADL: 'brush teeth' (5), Subject: 35, Session: 3

ADL: 'dusting' (22), Subject: 31, Session: 3

ADL: 'brush teeth' (5), Subject: 13, Session: 0

ADL: 'eat meal' (2), Subject: 40, Session: 3

ADL: 'open a bottle' (3), Subject: 32, Session: 4

ADL: 'put on a jacket' (8), Subject: 30, Session: 1

ADL: 'open a box' (4), Subject: 16, Session: 1

ADL: 'sit down' (13), Subject: 13, Session: 1

ADL: 'ironing' (23), Subject: 18, Session: 0

ADL: 'writing' (15), Subject: 37, Session: 2

ADL: 'writing' (15), Subject: 11, Session: 1

ADL: 'put on a jacket' (8), Subject: 16, Session: 2

ADL: 'open a box' (4), Subject: 2, Session: 3

ADL: 'open a box' (4), Subject: 30, Session: 2

ADL: 'sit down' (13), Subject: 35, Session: 2

ADL: 'writing' (15), Subject: 11, Session: 0

ADL: 'sit down' (13), Subject: 35, Session: 3

ADL: 'open a box' (4), Subject: 30, Session: 3

ADL: 'open a box' (4), Subject: 2, Session: 2

ADL: 'put on a jacket' (8), Subject: 16, Session: 3

ADL: 'sit down' (13), Subject: 13, Session: 0

ADL: 'open a box' (4), Subject: 16, Session: 0

ADL: 'put on a jacket' (8), Subject: 30, Session: 0

ADL: 'writing' (15), Subject: 37, Session: 3

ADL: 'ironing' (23), Subject: 18, Session: 1

ADL: 'stand up' (14), Subject: 22, Session: 4

ADL: 'eat meal' (2), Subject: 40, Session: 2

ADL: 'brush teeth' (5), Subject: 13, Session: 1

ADL: 'dusting' (22), Subject: 31, Session: 2

ADL: 'washing dishes' (24), Subject: 26, Session: 4

ADL: 'dusting' (22), Subject: 52, Session: 1

ADL: 'eat meal' (2), Subject: 23, Session: 1

ADL: 'put on a shoe' (9), Subject: 18, Session: 0

ADL: 'brush hair' (6), Subject: 48, Session: 0

ADL: 'put on a jacket' (8), Subject: 6, Session: 3

ADL: 'brush teeth' (5), Subject: 35, Session: 2

ADL: 'drink water' (1), Subject: 21, Session: 4

ADL: 'put on glasses' (11), Subject: 42, Session: 4

ADL: 'sneeze cough' (19), Subject: 9, Session: 2

ADL: 'phone call' (16), Subject: 30, Session: 3

ADL: 'stand up' (14), Subject: 19, Session: 2

ADL: 'sneeze cough' (19), Subject: 20, Session: 4

ADL: 'take off glasses' (12), Subject: 44, Session: 4

ADL: 'eat meal' (2), Subject: 1, Session: 1

ADL: 'brush teeth' (5), Subject: 5, Session: 3

ADL: 'ironing' (23), Subject: 40, Session: 4

ADL: 'phone call' (16), Subject: 16, Session: 0

ADL: 'salute' (18), Subject: 31, Session: 4

ADL: 'washing hands' (21), Subject: 14, Session: 2

ADL: 'blow nose' (20), Subject: 12, Session: 0

ADL: 'open a bottle' (3), Subject: 9, Session: 3

ADL: 'type on a keyboard' (17), Subject: 45, Session: 3

ADL: 'salute' (18), Subject: 5, Session: 1

ADL: 'washing hands' (21), Subject: 51, Session: 2

ADL: 'take off a shoe' (10), Subject: 30, Session: 4

ADL: 'type on a keyboard' (17), Subject: 26, Session: 0

ADL: 'washing hands' (21), Subject: 32, Session: 1

ADL: 'blow nose' (20), Subject: 34, Session: 3

ADL: 'put on a jacket' (8), Subject: 14, Session: 1

ADL: 'open a bottle' (3), Subject: 16, Session: 4

ADL: 'open a box' (4), Subject: 32, Session: 1

ADL: 'sit down' (13), Subject: 37, Session: 1

ADL: 'put on a jacket' (8), Subject: 51, Session: 1

ADL: 'writing' (15), Subject: 13, Session: 2

ADL: 'take off glasses' (12), Subject: 38, Session: 0

ADL: 'writing' (15), Subject: 35, Session: 1

ADL: 'open a box' (4), Subject: 51, Session: 2

ADL: 'sneeze cough' (19), Subject: 19, Session: 0

ADL: 'put on a jacket' (8), Subject: 32, Session: 2

ADL: 'open a box' (4), Subject: 14, Session: 2

ADL: 'sit down' (13), Subject: 11, Session: 2

ADL: 'stand up' (14), Subject: 2, Session: 1

ADL: 'take off a jacket' (7), Subject: 19, Session: 1

ADL: 'brush hair' (6), Subject: 29, Session: 1

ADL: 'brush teeth' (5), Subject: 11, Session: 3

ADL: 'dusting' (22), Subject: 33, Session: 0

ADL: 'eat meal' (2), Subject: 42, Session: 0

ADL: 'dusting' (22), Subject: 15, Session: 3

ADL: 'brush teeth' (5), Subject: 37, Session: 0

ADL: 'put on a jacket' (8), Subject: 4, Session: 1

ADL: 'eat meal' (2), Subject: 21, Session: 3

ADL: 'dusting' (22), Subject: 50, Session: 3

ADL: 'eat meal' (2), Subject: 3, Session: 3

ADL: 'writing' (15), Subject: 7, Session: 4

ADL: 'phone call' (16), Subject: 32, Session: 1

ADL: 'take off a jacket' (7), Subject: 2, Session: 1

ADL: 'writing' (15), Subject: 28, Session: 4

ADL: 'phone call' (16), Subject: 14, Session: 2

ADL: 'phone call' (16), Subject: 51, Session: 2

ADL: 'brush teeth' (5), Subject: 7, Session: 1

ADL: 'brush hair' (6), Subject: 1, Session: 4

ADL: 'washing dishes' (24), Subject: 39, Session: 3

ADL: 'salute' (18), Subject: 7, Session: 3

ADL: 'type on a keyboard' (17), Subject: 47, Session: 1

ADL: 'put on a shoe' (9), Subject: 21, Session: 4

ADL: 'take off a jacket' (7), Subject: 41, Session: 4

ADL: 'blow nose' (20), Subject: 10, Session: 2

ADL: 'washing hands' (21), Subject: 16, Session: 0

ADL: 'drink water' (1), Subject: 18, Session: 0

ADL: 'brush hair' (6), Subject: 34, Session: 4

ADL: 'blow nose' (20), Subject: 36, Session: 1

ADL: 'washing hands' (21), Subject: 30, Session: 3

ADL: 'type on a keyboard' (17), Subject: 24, Session: 2

ADL: 'put on glasses' (11), Subject: 18, Session: 3

ADL: 'stand up' (14), Subject: 26, Session: 0

ADL: 'sit down' (13), Subject: 52, Session: 4

ADL: 'put on a jacket' (8), Subject: 34, Session: 4

ADL: 'open a bottle' (3), Subject: 36, Session: 1

ADL: 'open a box' (4), Subject: 12, Session: 4

ADL: 'sit down' (13), Subject: 17, Session: 4

ADL: 'open a bottle' (3), Subject: 10, Session: 2

ADL: 'stand up' (14), Subject: 45, Session: 3

ADL: 'writing' (15), Subject: 50, Session: 4

ADL: 'phone call' (16), Subject: 29, Session: 2

ADL: 'writing' (15), Subject: 15, Session: 4

ADL: 'put on glasses' (11), Subject: 46, Session: 0

ADL: 'drink water' (1), Subject: 25, Session: 0

ADL: 'washing dishes' (24), Subject: 41, Session: 3

ADL: 'take off a jacket' (7), Subject: 39, Session: 4

ADL: 'put on glasses' (11), Subject: 25, Session: 3

ADL: 'type on a keyboard' (17), Subject: 9, Session: 1

ADL: 'washing dishes' (24), Subject: 22, Session: 0

ADL: 'washing hands' (21), Subject: 48, Session: 3

ADL: 'drink water' (1), Subject: 46, Session: 3

ADL: 'type on a keyboard' (17), Subject: 19, Session: 2

ADL: 'phone call' (16), Subject: 12, Session: 4

ADL: 'take off glasses' (12), Subject: 23, Session: 3

ADL: 'sneeze cough' (19), Subject: 47, Session: 3

ADL: 'ironing' (23), Subject: 44, Session: 0

ADL: 'put on a jacket' (8), Subject: 29, Session: 1

ADL: 'open a box' (4), Subject: 29, Session: 2

ADL: 'writing' (15), Subject: 1, Session: 2

ADL: 'put on a shoe' (9), Subject: 5, Session: 3

ADL: 'take off glasses' (12), Subject: 40, Session: 0

ADL: 'sit down' (13), Subject: 7, Session: 1

ADL: 'sneeze cough' (19), Subject: 24, Session: 0

ADL: 'ironing' (23), Subject: 27, Session: 3

ADL: 'ironing' (23), Subject: 2, Session: 1

ADL: 'salute' (18), Subject: 13, Session: 3

ADL: 'brush hair' (6), Subject: 14, Session: 1

ADL: 'put on a shoe' (9), Subject: 44, Session: 1

ADL: 'take off glasses' (12), Subject: 4, Session: 0

ADL: 'take off a jacket' (7), Subject: 24, Session: 1

ADL: 'take off a shoe' (10), Subject: 34, Session: 0

ADL: 'brush hair' (6), Subject: 51, Session: 1

ADL: 'brush hair' (6), Subject: 7, Session: 2

ADL: 'take off a shoe' (10), Subject: 12, Session: 3

ADL: 'put on a shoe' (9), Subject: 27, Session: 2

ADL: 'dusting' (22), Subject: 28, Session: 3

ADL: 'take off a jacket' (7), Subject: 47, Session: 2

ADL: 'blow nose' (20), Subject: 16, Session: 4

ADL: 'salute' (18), Subject: 35, Session: 0

ADL: 'brush hair' (6), Subject: 32, Session: 2

ADL: 'phone call' (16), Subject: 48, Session: 3

ADL: 'open a bottle' (3), Subject: 34, Session: 3

ADL: 'stand up' (14), Subject: 24, Session: 2

ADL: 'ironing' (23), Subject: 38, Session: 4

ADL: 'open a box' (4), Subject: 4, Session: 4

ADL: 'stand up' (14), Subject: 47, Session: 1

ADL: 'open a bottle' (3), Subject: 12, Session: 0

ADL: 'salute' (18), Subject: 49, Session: 4

ADL: 'washing dishes' (24), Subject: 43, Session: 1

ADL: 'washing hands' (21), Subject: 29, Session: 2

ADL: 'drink water' (1), Subject: 27, Session: 2

ADL: 'put on glasses' (11), Subject: 44, Session: 2

ADL: 'eat meal' (2), Subject: 46, Session: 4

ADL: 'dusting' (22), Subject: 37, Session: 4

ADL: 'take off a shoe' (10), Subject: 48, Session: 4

ADL: 'drink water' (1), Subject: 44, Session: 1

ADL: 'washing dishes' (24), Subject: 20, Session: 2

ADL: 'put on glasses' (11), Subject: 27, Session: 1

ADL: 'ironing' (23), Subject: 46, Session: 2

ADL: 'sneeze cough' (19), Subject: 45, Session: 1

ADL: 'take off glasses' (12), Subject: 21, Session: 1

ADL: 'open a box' (4), Subject: 48, Session: 3

ADL: 'put on a jacket' (8), Subject: 48, Session: 0

ADL: 'ironing' (23), Subject: 25, Session: 1

ADL: 'sneeze cough' (19), Subject: 26, Session: 2

ADL: 'washing hands' (21), Subject: 9, Session: 2

ADL: 'sit down' (13), Subject: 5, Session: 3

ADL: 'take off glasses' (12), Subject: 42, Session: 2

ADL: 'writing' (15), Subject: 3, Session: 0

ADL: 'put on a shoe' (9), Subject: 7, Session: 1

ADL: 'take off a shoe' (10), Subject: 36, Session: 2

ADL: 'dusting' (22), Subject: 49, Session: 2

ADL: 'eat meal' (2), Subject: 38, Session: 2

ADL: 'take off a jacket' (7), Subject: 26, Session: 3

ADL: 'take off glasses' (12), Subject: 6, Session: 2

ADL: 'put on a shoe' (9), Subject: 46, Session: 3

ADL: 'brush hair' (6), Subject: 16, Session: 3

ADL: 'salute' (18), Subject: 11, Session: 1

ADL: 'brush hair' (6), Subject: 30, Session: 0

ADL: 'salute' (18), Subject: 37, Session: 2

ADL: 'washing hands' (21), Subject: 12, Session: 4

ADL: 'take off a jacket' (7), Subject: 45, Session: 0

ADL: 'put on a shoe' (9), Subject: 25, Session: 0

ADL: 'take off a shoe' (10), Subject: 10, Session: 1

ADL: 'brush hair' (6), Subject: 5, Session: 0

ADL: 'salute' (18), Subject: 11, Session: 3

ADL: 'put on a shoe' (9), Subject: 46, Session: 1

ADL: 'type on a keyboard' (17), Subject: 20, Session: 4

ADL: 'take off glasses' (12), Subject: 6, Session: 0

ADL: 'brush hair' (6), Subject: 16, Session: 1

ADL: 'take off a jacket' (7), Subject: 26, Session: 1

ADL: 'dusting' (22), Subject: 49, Session: 0

ADL: 'eat meal' (2), Subject: 38, Session: 0

ADL: 'take off a shoe' (10), Subject: 36, Session: 0

ADL: 'blow nose' (20), Subject: 51, Session: 4

ADL: 'brush hair' (6), Subject: 5, Session: 2

ADL: 'take off a shoe' (10), Subject: 10, Session: 3

ADL: 'put on a shoe' (9), Subject: 25, Session: 2

ADL: 'blow nose' (20), Subject: 14, Session: 4

ADL: 'take off a jacket' (7), Subject: 45, Session: 2

ADL: 'salute' (18), Subject: 37, Session: 0

ADL: 'brush hair' (6), Subject: 30, Session: 2

ADL: 'open a box' (4), Subject: 48, Session: 1

ADL: 'phone call' (16), Subject: 10, Session: 4

ADL: 'take off glasses' (12), Subject: 21, Session: 3

ADL: 'sneeze cough' (19), Subject: 45, Session: 3

ADL: 'ironing' (23), Subject: 46, Session: 0

ADL: 'open a bottle' (3), Subject: 29, Session: 4

ADL: 'put on a shoe' (9), Subject: 7, Session: 3

ADL: 'writing' (15), Subject: 3, Session: 2

ADL: 'take off glasses' (12), Subject: 42, Session: 0

ADL: 'sit down' (13), Subject: 5, Session: 1

ADL: 'sneeze cough' (19), Subject: 26, Session: 0

ADL: 'washing hands' (21), Subject: 9, Session: 0

ADL: 'ironing' (23), Subject: 25, Session: 3

ADL: 'put on a jacket' (8), Subject: 48, Session: 2

ADL: 'put on glasses' (11), Subject: 44, Session: 0


In [ ]:
final_df = pd.concat(all_data, ignore_index=True)
final_df = final_df[['timestamp', 'accX[mg]', 'accY[mg]', 'accZ[mg]', 'adl', 'session', 'subject', 'fileID']] # Reorder columns

final_df

,timestamp,accX[mg],accY[mg],accZ[mg],adl,session,subject,fileID
0,0.00,-1187.500,125.000,-625.000,7,1,45,1
1,31.25,-859.375,109.375,-531.250,7,1,45,1
2,62.50,-828.125,62.500,-500.000,7,1,45,1
3,93.75,-843.750,78.125,-421.875,7,1,45,1
4,125.00,-1000.000,125.000,-453.125,7,1,45,1
...,...,...,...,...,...,...,...,...
1432168,3500.00,-156.250,-812.500,343.750,18,4,24,6072
1432169,3531.25,109.375,-828.125,515.625,18,4,24,6072
1432170,3562.50,62.500,-750.000,265.625,18,4,24,6072
1432171,3593.75,0.000,-703.125,218.750,18,4,24,6072
1432172,3625.00,-656.250,-687.500,546.875,18,4,24,6072

In [ ]:
# Save the DataFrame after cleaning the inactive movements
output_file = f"../Data/PAAL_ADL/Processed/PAAL_ADL_{fs}hz.csv"

# Remove the dataset file if it already exists
if os.path.exists(output_file):
    os.remove(output_file)
    print(f"{output_file} has been removed successfully.")
else:
    print(f"{output_file} does not exist.")

# Save processed data
final_df.to_csv(output_file, index=False)
print(f"The dataset was saved to {output_file}")

../Data/PAAL_ADL/Processed/PAAL_ADL_32hz.csv does not exist.
The dataset was saved to ../Data/PAAL_ADL/Processed/PAAL_ADL_32hz.csv